spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/carpool_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Gate@2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


del
app.jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUVG9rZW5HZW5lcmF0aW9uMTIz
app.jwt.expiration=86400000



# Set level for your whole package
logging.level.com.carPooling.backend=DEBUG

# Set level for a specific class
#logging.level.com.carPooling.backend.service.impl.AuthServiceImplements=TRACE

# Spring Security logs (very useful for auth debugging)
logging.level.org.springframework.security=DEBUG

# Log to a file as well (optional)
logging.file.name=logs/app.log

#Trace, Debug, Info, Warn, Error, Fatal

server.port=8089


